spring:
  ai:
    model:
      chat: bedrock-converse
    bedrock:
      aws:
        region: us-east-1
        access-key: "${aws-access-key}"
        secret-key: "${aws-secret-key}"
      converse:
        chat:
          options:
            model: "us.anthropic.claude-sonnet-4-5-20250929-v1:0"

  autoconfigure:
    exclude:
      - org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration