spring:
  application:
    name: SpringAI
  ai:
    chat:
      client:
        enabled: true
    openai:
      api-key: ${OPENAI_API_KEY:}
    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: llmtest

  devtools:
    restart:
      enabled: false
  config:
    import: classpath:h2-db-file.properties
  docker:
    compose:
      stop:
        command: DOWN

springdoc:
  api-docs:
    path: /api-docs

logging:
  pattern:
    console: '%green(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %blue(%-5level) %yellow(%logger{36}) - %msg%n'
  level:
    org.springframework.ai.chat.client.advisor: debug